### ISSUE TITLE
Crash with Metrics

### ISSUE THREAD

**Issue by StanKocken** [bitstadium/HockeySDK-Android#196] opened 2016-12-19 11:32 UTC
The biggest crash I have with my app is coming from… my crash reporter.

	java.lang.RuntimeException: An error occured while executing doInBackground()
		at android.os.AsyncTask$3.done(AsyncTask.java:300)
		at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
		at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
		at java.util.concurrent.FutureTask.run(FutureTask.java:242)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
		at java.lang.Thread.run(Thread.java:841)
	Caused by: java.lang.SecurityException: Permission denied (missing INTERNET permission?)
		at java.net.InetAddress.lookupHostByName(InetAddress.java:437)
		at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
		at java.net.InetAddress.getAllByName(InetAddress.java:214)
		at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
		at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216)
		at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122)
		at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:292)
		at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
		at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
		at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
		at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
		at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
		at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
		at net.hockeyapp.android.metrics.Sender.getWriter(Sender.java:398)
		at net.hockeyapp.android.metrics.Sender.logRequest(Sender.java:320)
		at net.hockeyapp.android.metrics.Sender.send(Sender.java:141)
		at net.hockeyapp.android.metrics.Sender.sendAvailableFiles(Sender.java:126)
		at net.hockeyapp.android.metrics.Sender$1.doInBackground(Sender.java:86)
		at net.hockeyapp.android.metrics.Sender$1.doInBackground(Sender.java:82)
		at android.os.AsyncTask$2.call(AsyncTask.java:288)
		at java.util.concurrent.FutureTask.run(FutureTask.java:237)
		... 3 more
	Caused by: libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
		at libcore.io.Posix.getaddrinfo(Posix.java)
		at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61)
		at java.net.InetAddress.lookupHostByName(InetAddress.java:412)
		... 23 more
	Caused by: libcore.io.ErrnoException: getaddrinfo failed: EACCES (Permission denied)
		... 26 more

Of course I do have the permission Internet.
I cannot reproduce it locally, there are only reports from my crash reporters (on hockey app but also on others).

Thanks.

**Comment by ranterle** [comment] 2016-12-19 14:41
Hi @StanKocken, that of course would terrible if the crash reporter would be causing crashes itself.
Unfortunately, like you, we are not able to reproduce this scenario, is it possibly linked to a specific device manufacturer, model, or OS version, that you can see from the analysis?

Finally: If your app were not to have the `INTERNET` permission, how would the crash reports reach you/the crash reporter backends? That leads me to believe there must be a different background to this.

**Comment by StanKocken** [comment] 2016-12-19 14:46
It seems not to be device specific: 
<img width="1117" alt="screen shot 2016-12-19 at 15 42 36" src="https://cloud.githubusercontent.com/assets/2204411/21316614/cdfb7f20-c601-11e6-9cb9-7a0509d68163.png">

70% on Samsung (which is normal because Samsung got a big part of the market), 9% on LG, 6% on Sony…
65% on Android 4.x and 35% on Android 5.x (including 5.1.1). It is NOT present on 6+.
On the latest build it's only on 4.4.x. 

Note, I did update to the latest HockeyApp SDK and nothing changed.
Worst is that I cannot catch this error as it's on another thread.

**Comment by ranterle** [comment] 2017-01-17 02:31
After revisiting this, I still can't make sense of it - is your code running in a separate process somehow, maybe through a service?
Can you provide an isolated code sample? If that's not possible, can you share your problem with code in our [support forum](https://support.hockeyapp.net)?

**Comment by StanKocken** [comment] 2017-01-17 10:04
FYI, I removed any calls to Metrics to avoid this crash. So I'm not using this service anymore.
I was never able to reproduce it locally, only on some production users (and not all of them like 0.5%, but still my bigger crash)

**Comment by ranterle** [comment] 2017-01-17 16:23
That's very unfortunate - I'm afraid we can't reproduce the issue right now.

**Comment by TroubleMakerBen** [comment] 2017-03-31 16:38
I wonder if `Caused by: java.lang.SecurityException: Permission denied (missing INTERNET permission?)` indicates that a user removed the internet permission for the app? 🤔

**Comment by TroubleMakerBen** [comment] 2017-04-27 01:54
Hey Stan,
We just released version 4.1.4 that comes with a fix for this.
Thanks for using HockeyApp and let me know in case you run into other issues, have some feedback, etc..
Take care!
Benny

**Closed by TroubleMakerBen** 2017-04-27 01:54 UTC
