### ISSUE TITLE
Transmission Failed

### ISSUE THREAD

**Issue by caltseng** [bitstadium/HockeySDK-Android#105] opened 2015-11-13 18:44 UTC
Since upgrading to version 3.6.2, hockeyapp seems to fail transmission quite often. We are missing crash logs for much of yesterday (11/12/15). Has there been server issue, or is there something wrong with this new version of the Android SDK?

11-13 09:29:59.502 D/HockeyApp: Date: Fri Nov 13 07:42:39 PST 2015
11-13 09:30:01.826 D/HockeyApp: Transmission failed, will retry on next register() call
11-13 09:30:01.881 D/HockeyApp: Transmitting crash data: 
11-13 09:30:01.881 D/HockeyApp: Package: XXXX.XXXX.XXXX
11-13 09:30:01.881 D/HockeyApp: Version Code: XXXXX
11-13 09:30:01.881 D/HockeyApp: Version Name: XXX
11-13 09:30:01.881 D/HockeyApp: Android: 5.1.1
11-13 09:30:01.881 D/HockeyApp: Manufacturer: LGE
11-13 09:30:01.881 D/HockeyApp: Model: Nexus 5

**Comment by ranterle** [comment] 2015-11-15 13:43
Hi @caltseng - we added some network connectivity checks [in 3.6.2](https://github.com/bitstadium/HockeySDK-Android/blob/df16af7e9ff3c251e30abdce238eb441f07531a0/src/main/java/net/hockeyapp/android/CrashManager.java#L538) but this seems to be a different kind of issue, since the connectivity checks have already passed at the point of your reports.
We didn't have any outages and have not had any reports for submissions failing for 3.6.2 so far, do you have more details about the time and location of the failed attempts?
If this issue is persisting I would greatly appreciate your help in tracking it down.

**Comment by caltseng** [comment] 2015-11-16 21:58
Hmm. I ran into this today. Not sure if this is an issue with your code or with ours or just some weird network issues..

> W/System.err﹕ java.io.InterruptedIOException: thread interrupted
W/System.err﹕ at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
W/System.err﹕ at com.android.okhttp.okio.Okio$1.write(Okio.java:73)
W/System.err﹕ at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
W/System.err﹕ at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
W/System.err﹕ at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
W/System.err﹕ at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:52)
W/System.err﹕ at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:902)
W/System.err﹕ at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
W/System.err﹕ at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
W/System.err﹕ at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
W/System.err﹕ at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
W/System.err﹕ at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
W/System.err﹕ at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
W/System.err﹕ at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:132)
W/System.err﹕ at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:58)
W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:295)
W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err﹕ at java.lang.Thread.run(Thread.java:818)

**Comment by ranterle** [comment] 2015-11-16 22:00
This can't be our SDK code - we don't use OkHttp or any other HTTP library.

**Comment by caltseng** [comment] 2015-11-16 22:01
Hmm okay there's something wrong for us then. 

We'll look into it and I'll let you know if the problem persists. Thanks.

**Comment by raviteja06** [comment] 2016-01-19 11:49
I am also getting the same kind of issue.

It is pointing to net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:137)

In my project, i am using retrofit with okhttp. Can you please cross check if that might be causing this issue.

Thanks in advance.

**Comment by ranterle** [comment] 2016-01-19 12:49
Hi @raviteja06,
which version of the SDK are you using in your app? What is the detailed stacktrace?
Please open a [support request](http://support.hockeyapp.net/) with us and address it to me directly if this information should be kept private.

Best,
Mat

**Comment by raviteja06** [comment] 2016-01-19 14:01
Hi Mat,

SDK version: 3.7.0
Android 6.0

Stacktrace:
```
01-19 19:21:02.413 6978-6978/? I/art: Late-enabling -Xcheck:jni
01-19 19:21:02.444 6978-6985/? I/art: Debugger is no longer active
01-19 19:21:02.469 6978-6978/? I/MultiDex: VM with version 2.1.0 has multidex support
01-19 19:21:02.469 6978-6978/? I/MultiDex: install
01-19 19:21:02.469 6978-6978/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
01-19 19:21:02.504 6978-7008/? I/GMPM: App measurement is starting up
01-19 19:21:02.517 6978-6978/? W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
01-19 19:21:03.209 6978-6978/? D/HockeyApp: Looking for exceptions in: /data/user/0/com.example/files
01-19 19:21:03.210 6978-6978/? D/HockeyApp: Current handler class = com.android.internal.os.RuntimeInit$UncaughtHandler
01-19 19:21:03.350 6978-6978/? D/HockeyApp: Looking for exceptions in: /data/user/0/com.example/files
01-19 19:21:03.351 6978-6978/? D/HockeyApp: Current handler class = net.hockeyapp.android.ExceptionHandler
01-19 19:21:03.829 6978-7029/com.example W/System.err: java.io.InterruptedIOException: thread interrupted
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.okio.Okio$1.write(Okio.java:73)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:52)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:902)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:138)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:66)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-19 19:21:03.830 6978-7029/com.example W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

As i mentioned in previous comment. I am using OKHTTP and retrofit. Let me know if you need more info.

**Comment by ranterle** [comment] 2016-01-19 16:46
This doesn't look like an error caused by our AsyncTask but more like flaky or no network causing the HTTP stack to crash.
Can you reproduce the issue? If yes, do you see a pattern how and when this occurs?

**Comment by raviteja06** [comment] 2016-01-19 18:12
Mat, 


It happens every time when I start an activity. Can be reproducible every time. The devices I tested are nexus 6p and moto G3. 


I recently came across similar issue and found out Google made changes to android 6.0 http stack. They removed support to apache http client.


http://stackoverflow.com/questions/32071025/apache-http-connection-with-android-6-0-marshmallow


But I see the error is throwing by okhttp. So may be give a shot by creating a project with hockey, retrofit and okhttp as dependencies in android 6.0. 


Tomorrow I will test to see same behavior on android lollipop or lesser. Will keep you update.


Thanks,

----------------

Best Regards,

Ravi Gadipudi


From: Mat

Sent: Tuesday, January 19, 10:16 PM

Subject: Re: [HockeySDK-Android] Transmission Failed (#105)

To: bitstadium/HockeySDK-Android

Cc: Ravi Gadipudi


Reopened #105.


—

Reply to this email directly or view it on GitHub.





On Tue, Jan 19, 2016 at 8:46 AM -0800, "Mat" <notifications@github.com> wrote:












Reopened #105.

**Comment by raviteja06** [comment] 2016-01-20 03:58
@ranterle I am only seeing this on phones running android 6.0 and above.

**Comment by ranterle** [comment] 2016-01-21 20:06
What's the code of the activity doing - is it any activity of your app or a particular one?
We are aware of the changes to the HTTP stack in Android 6.0 and have completely rebuilt our library to not use Apache HttpClient anymore.
I'm trying to find the most specific scenario to be able to isolate the issue, so far I had no luck reproducing it. Feel free to take this to a private discussion if you have to share code.

**Comment by raviteja06** [comment] 2016-02-03 14:44
@ranterle I made some changes I code. But now I am not seeing this issue. Will update if I see it again. and will also post what I did to fix this issue.

**Comment by TroubleMakerBen** [comment] 2016-02-17 16:55
@raviteja06 any news on this, I'll close this other otherwise.

**Comment by TroubleMakerBen** [comment] 2016-03-01 22:36
Closing this as we haven't heard back. Please let us know in case you continue seeing this.

**Closed by TroubleMakerBen** 2016-03-01 22:36 UTC
