### ISSUE TITLE
Weird error log on logcat relating to updates in hockey sdk

### ISSUE THREAD

**Issue by jojonarte** [bitstadium/HockeySDK-Android#343] opened 2017-12-21 10:35 UTC
```
12-21 18:33:14.310 3389-3430/com.myapp E/HockeyUpdate: Could not fetch updates although connected to internet
                                                                  java.io.InterruptedIOException: thread interrupted
                                                                      at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
                                                                      at com.android.okhttp.okio.Okio$1.write(Okio.java:78)
                                                                      at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
                                                                      at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
                                                                      at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
                                                                      at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:60)
                                                                      at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1147)
                                                                      at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:980)
                                                                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:482)
                                                                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
                                                                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:235)
                                                                      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                                                                      at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:112)
                                                                      at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:38)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
```

**Comment by MatkovIvan** [comment] 2017-12-21 10:41
Hi @jojonarte 

Thanks for getting in touch.
It looks like just network timeout. Maybe do you have some other details (steps to repro, SDK version etc.)?

Best,
Ivan

**Comment by jojonarte** [comment] 2017-12-21 12:42
Hi @MatkovIvan 
Here are a few more details:
```
android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId 'com.myapp'
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 48
        versionName '3.8.20'
        manifestPlaceholders = [HOCKEYAPP_APP_ID: "IDIDIDIDIDDI"]
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true //
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        targetCompatibility 1.7
        sourceCompatibility 1.7
    }
    productFlavors {
    }
}
```
To reproduce:
The log just appears everytime I launch the app.

**Comment by bmourat** [comment] 2017-12-26 13:08
Hi @jojonarte!

How often does this happen and what are doing when this error appears?

Best,
Murat

**Comment by bmourat** [comment] 2017-12-26 13:21
Hi @jojonarte 

Is this issue still happening everytime you launch your app? If so, could you check if this address
https://sdk.hockeyapp.net/api/2/apps/
is reachable on your device?
Also, could you please provide following info:
1. How are you registering UpdateManager?
2. When in the app lifecycle UpdateManager.register is called?
3. The version of HockeySDK you are using?

Bets,
Murat

**Comment by jojonarte** [comment] 2017-12-27 02:00
UpdateManager.register is called when the activity gets created or resumed, and unregistered on stop and onDestroy.

**Comment by TroubleMakerBen** [comment] 2018-01-02 17:37
Hey @jojonarte,

I'm trying to repro this issue. Which HockeySDK version are you using?
In addition, can you provide more info on when exactly you are calling `register()` etc?

You can reach the team via email (appcentersdk@microsoft.com) or through [support](https://support.hockeyapp.net) and share the info there in a confidential way.

Best,
Benjamin

**Comment by TroubleMakerBen** [comment] 2018-01-10 01:10
Hey @jojonarte,

is this still an issue for you?

Best,
Benjamin

**Comment by TroubleMakerBen** [comment] 2018-01-10 23:57
Closing this as we haven't heard back. Feel free to reopen if necessary.

**Comment by ZeAleks** [comment] 2018-02-04 15:38
Hello,

I do have the same error.
I didn't work on my app for a long time ago. Everything was working but now I have this very message.
I tried the url above and it seems to work on my device. I get a json message "no api taken".

The CrashManager.Register is called in the OnCreate override of my main (first) Activity.

I'm now using Visual Studio 2017 and I have the last hockeySdk.xamarin installed (5.1.2).

Can you help ?

Thank you.

**Comment by bmourat** [comment] 2018-02-05 09:20
Hi @ZeAleks 

Could you provide info on how are you registering your UpdateManager, since the original error concerns updates functionality and stacktrace of your error?

**Comment by TroubleMakerBen** [comment] 2018-02-05 17:36
@ZeAleks @bmourat Please continue this discussion in the Xamarin repo as this seems to be a Xamarin issue -> [#116](https://github.com/bitstadium/HockeySDK-Xamarin/issues/116)

**Comment by ZeAleks** [comment] 2018-02-06 03:51
@TroubleMakerBen , I don't think it is a Xamarin issue.

Here is the stacktrace :
`02-04 11:31:04.204 E/HockeyUpdate(14335): Could not fetch updates although connected to internet
02-04 11:31:04.204 E/HockeyUpdate(14335): java.io.InterruptedIOException: thread interrupted
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.okio.Okio$1.write(Okio.java:73)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:225)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:52)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:916)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:802)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:460)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:112)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:38)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-04 11:31:04.204 E/HockeyUpdate(14335): 	at java.lang.Thread.run(Thread.java:818)`

The updateManager is called at the same time that CrashManager (OnCreate). I'm checking if I am in debug mode to do that (and it is the case here).

Thank you.

**Comment by MatkovIvan** [comment] 2018-02-07 13:27
Hi @ZeAleks and @jojonarte

This error means that background task with network request for checking updates was interrupted. After a closer look I saw two possible ways how this can happen:
1. Timeout. It's 30 sec for default android background tasks;
2. Force cancel task by call `UpdateManager.unregister()` API;

So, could you please recheck when you call `unregister` function? If you call it on some activity life event, make sure that activity doesn't disappear immediately.

Best,
Ivan

**Comment by ZeAleks** [comment] 2018-02-08 22:48
OK Matkovlan,

So I'm calling the unregister function in OnPause and OnDestroy.

But everything was working before I migrated to a new version of hockeySDK (and Visual Studio 2017).

**Comment by MatkovIvan** [comment] 2018-02-21 17:32
Hi @ZeAleks

Is this still issue for you? Let me know if you need help with that.
Please note that you don't need to call `unregister()` in on pause event if you already have that on destroy.
Also,
> make sure to always balance register(...) calls to SDK managers with unregister() calls

You can check details and example in our [doc](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#2-6-add-update-distribution):

Some summary regarding this error:
`unregister()` **breaks**  checking updates process and you can see this error message in logs. If you get it always please make sure **you do not call** `unregister()` immediately (or very shortly) after appication start (`register()` call).

**Comment by ZeAleks** [comment] 2018-02-22 00:43
Hi Ivan,

Yes I have this issue still now.
The error appear before any call to unregister and after the call to register.

**Comment by MatkovIvan** [comment] 2018-02-22 09:47
@ZeAleks Do you able to reproduce it on a blank project? Could you please share reproduction sample?
I managed to get this error only in the case where I manually broke checking updates process by `unregister()` call.

**Comment by ZeAleks** [comment] 2018-02-24 02:30
OK

Give the Week-end to find a moment to make a repro if I can.
Thanks for your help.

**Comment by ZeAleks** [comment] 2018-02-26 03:10
Hey,

I was not able to reproduce the error.
Don't know what happen. I was not working on this project and everything is ok now.

The only thing I did yesterday is upgrading VS 2017 from 15.5.6 to 15.5.7.

Thank you for your help Ivan.
I hope the error will not come back.

**Comment by MatkovIvan** [comment] 2018-02-26 06:10
@ZeAleks You are welcome.
Let us know if you face it again.

**Comment by TroubleMakerBen** [comment] 2018-02-26 18:41
I'm closing this @ZeAleks but please just reopen and get in touch over at [support](https://support.hockeyapp.net) – we're here for you.

**Closed by TroubleMakerBen** 2018-02-26 18:41 UTC

**Comment by AngryITGuy** [comment] 2018-08-13 04:46
Late to this thread, but was having this issue in Android. Same sort of setup, nothing exotic in my build.gradle or manifest. I was doing this check during my startup activity (ie splash). When I was reviewing the stacktrace, this line lead me to a solution

> "java.io.InterruptedIOException: thread interrupted"

I was not waiting for the UpdateManager to complete its check with HockeyApp. Thus, the thread has been "interrupted". You can try waiting for the update check to complete. 

So, I created a class that implemented UpdateManagerListener and called the register event with my listener. Within the listener, if noUpdateAvailable is triggered, I continue running what i need to do :

```
private class HockeyUpdateListener extends UpdateManagerListener {
        Context mContext;

        public HockeyUpdateListener(Context context) {
            this.mContext = context;

        }
        @Override
        public void onUpdateAvailable() {
            // do standard or custom update behaviour here.
            super.onUpdateAvailable();
        }

        @Override
        public void onNoUpdateAvailable() {
            // continue running the app.
        }
    }
```

**Comment by AngryITGuy** [comment] 2018-08-13 07:55
@MatkovIvan happy to share. With all due respect, I know English is not your first language and it did not read clearly. Explicitly stating the method, register(Activity, UpdateManagerListener), would make reading easier.
