### ISSUE TITLE
Confirmation Dialog "Send Report" is cut off

### ISSUE THREAD

**Issue by TroubleMakerBen** [bitstadium/HockeySDK-Android#149] opened 2016-04-08 20:33 UTC
On a Samsung Galaxy S4, running Android 5, the confirmation dialog text "Send Report" is cut off, it says "Send Repo".
SDK Version: 4.1.0-beta.1

Reported by @chrwend. I will look into this.

**Comment by ranterle** [comment] 2016-11-15 02:26
Closing as not able to reproduce.

**Closed by ranterle** 2016-11-15 02:26 UTC
Labels: bug
