### ISSUE TITLE
Auto upload cannot be disabled when user picks "always send"

### ISSUE THREAD

**Issue by niedzielski** [bitstadium/HockeySDK-Android#93] opened 2015-09-11 15:52 UTC
Returning false from CrashManagerListener.shouldAutoUploadCrashes() has no effect when the user picks "always send". Maybe this callback should instead be passed a boolean indicating the user preference but have control over whether to ignore that preference or not.

**Comment by ashtom** [comment] 2015-09-11 15:53
What's the use case for this? The user can only pick "Always Send" after he had seen the dialog for the first time. Do you want to force him to see the dialog again even though he picked "Always Send"?

**Comment by niedzielski** [comment] 2015-09-15 00:06
@ashtom, we expose the setting in case the user wants to change their mind.

**Comment by ranterle** [comment] 2015-11-15 13:43
Will reinvestigate for the next iteration when we have time.

**Comment by ranterle** [comment] 2016-07-01 08:17
Closing this as duplicate of #92.

**Closed by ranterle** 2016-07-01 08:17 UTC
