### ISSUE TITLE
No Update-Check on Android 7.0

### ISSUE THREAD

**Issue by UlfHesselbarth** [bitstadium/HockeySDK-Android#195] opened 2016-12-15 16:21 UTC
The HockeyApp-SDK (4.1.2) UpdateManager does not start an update task on my Nexus 9 even though it should.
While debugging the problem I found this particular piece of code in `UpdateManager::installedFromMarket`:

` if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N && TextUtils.equals(installer, INSTALLER_PACKAGE_INSTALLER_NOUGAT)) {
                        result = false;
                    }`

The package name for the installer is statically defined as:

`public static final String INSTALLER_PACKAGE_INSTALLER_NOUGAT = "com.google.android.packageinstaller";`

On my Nexus 9 however, the installer package name is actually: `com.android.packageinstaller`. This leads to the UpdateManager thinking the App was installed from the market (which it wasn't) so no update check is triggered.

**Comment by ranterle** [comment] 2016-12-15 19:28
Hi @UlfHesselbarth thanks for reporting this - I'll be working to verify this on a device and will add a fix for that.

**Comment by ranterle** [comment] 2016-12-19 15:49
That's odd, I checked on both a Nexus 9 hardware device with Android 7.0 and an emulator with 7.0 installed and both reported the package installer as `com.google.android.packageinstaller` just what our previous tests returned.

**Comment by UlfHesselbarth** [comment] 2016-12-19 15:56
Interesting. Not sure what's so different about our device. Let me know if there's something we can do to help figure this out.

**Comment by ranterle** [comment] 2016-12-19 16:14
What's the process you used to extract the installer name?
I uploaded the APK to HockeyApp and installed it from there. Then hooked up the debugger to the running app and extracted the value of https://github.com/bitstadium/HockeySDK-Android/blob/f26511ac2f27379ddaf9db92affb79079ded6315/hockeysdk/src/main/java/net/hockeyapp/android/UpdateManager.java#L221

**Comment by UlfHesselbarth** [comment] 2016-12-19 16:16
That is exactly what I did the first time :)

**Comment by virat-shukla** [comment] 2016-12-28 08:03
Actually i tried with Android api 23, its not checking for update.

**Comment by ranterle** [comment] 2017-01-17 16:28
Looks like we need more information to possibly reproduce this.
For @UlfHesselbarth the installer package name is `com.android.packageinstaller` - @virat-shukla can you confirm this is the package name in your case as well?

We haven't seen this name before, I'd feel ok about adding this check if there were multiple confirmed cases of this particular one.

**Comment by virat-shukla** [comment] 2017-01-25 05:03
@ranterle Actually it got fixed, there was a check in my application lifecycle so that it would only check it once. Somebody messed it up. Now its fixed. Its working fine on both Android 7.0 and 7.1.1. Sorry for misunderstanding.

**Comment by ranterle** [comment] 2017-01-25 09:56
@virat-shukla Good to know, no worries 👍

**Comment by TroubleMakerBen** [comment] 2017-02-09 18:56
Closing this as the issue is resolved. =)

**Closed by TroubleMakerBen** 2017-02-09 18:56 UTC
