### ISSUE TITLE
Util.isConnectedToNetwork crashes if ACCESS_NETWORK_STATE is revoked / not granted

### ISSUE THREAD

**Issue by aromanovsky** [bitstadium/HockeySDK-Android#172] opened 2016-08-26 02:37 UTC
Since Android M[arshmallow], the user can revoke previously granted permission groups, such as network state access. The CrashManager#sendCrashes() method handles many obstacles gracefully, however this one causes a SecurityException with the following trace:

java.lang.SecurityException: ConnectivityService: Neither user 10171 nor current process has android.permission.ACCESS_NETWORK_STATE.
    at android.os.Parcel.readException(Parcel.java:1599)
    at android.os.Parcel.readException(Parcel.java:1552)
    at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1538)
    at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:923)
    at net.hockeyapp.android.utils.Util.isConnectedToNetwork(SourceFile:271)
    at net.hockeyapp.android.CrashManager.sendCrashes(SourceFile:558)
    at net.hockeyapp.android.CrashManager.sendCrashes(SourceFile:546)
    at net.hockeyapp.android.CrashManager.execute(SourceFile:204)
    at net.hockeyapp.android.CrashManager.register(SourceFile:143)
    at net.hockeyapp.android.CrashManager.register(SourceFile:128)

There is no clean way to bypass this check and retry blindly (which is a perfectly legitimate scenario) other than intercept the SecurityException and call CrashManager#submitStackTraces() directly.

**Comment by ranterle** [comment] 2016-08-30 06:26
Hi @aromanovsky, thanks for reporting this. 
In my testing, the `ACCESS_NETWORK_STATE` permission is not presented to the user for granting, it is in the [Normal Permissions group](https://developer.android.com/guide/topics/security/normal-permissions.html) - so to my knowledge, the user can only revoke this permission using ADB.

To mitigate the crash:
The originating method `Util.isConnectedToNetwork(…)` is used in several places. As the crash reporting does not have UI at this point, we can only log an error to the console then.

**Comment by aromanovsky** [comment] 2016-08-30 06:45
Logging is good enough. I would also suggest returning true then so that code that relied on prior network availability knowledge tried the network operation anyway. (And if it fails, it would result in nothing worse than a further retry at a later time.)

**Comment by ranterle** [comment] 2016-08-30 07:09
Unfortunately this is not entirely possible - some of the network calls would fail and could cause crashes. The permission not being granted is an edge case as laid out before, so I think the better behavior is to stop right there.

**Comment by aromanovsky** [comment] 2016-08-30 07:25
Unfortunately, I would consider it in irrecoverable regression and advise my team to stick to the existing version then.
1. No I/O operation can be guaranteed to complete in a predictable fashion. Going out of network coverage / switching networks / hitting a "Sign in to WiFi" proxy wall / radio jam from magnetic storms would stay possible in all cases.
2. Network calls throw a checked IOException. There is no way to miss it. There is also no way to mishandle it by rethrowing it as unchecked (RTE etc.) without a rainfall of crashes for reasons listed in (1).
3. On the contrary, assuming "no right to know the network state" to mean "no network" would cut reports from users deliberately revoking the permission entirely.

Another _graceful_ way to go (other than assuming "true") would be giving the client app control over the default value.
An even more graceful way to go would be extracting the condition as a settable/injectable strategy.

**Comment by ranterle** [comment] 2016-08-30 08:00
We have had weird uncaught exceptions and error scenarios even though we employed checks in the respective areas on several occasions. Unfortunately, errors are often not reproducible because only limited information is available. This prompted us to add this network connectivity check in the CrashManager.

Generally speaking, what would be the motivation of a user to be deliberately revoking the permission to access the network state but allowing for the app to try and transmit data anyway without e.g. revoking the `INTERNET` permission anyway?

Also, I tried revoking the `ACCESS_NETWORK_STATE` permission via ADB - it only returned

```
Operation not allowed: java.lang.SecurityException: Permission android.permission.ACCESS_NETWORK_STATE is not a changeable permission type
```

So, how would one revoke this particular permission anyway?

**Comment by aromanovsky** [comment] 2016-08-30 08:18
However the motivation the scenario is legitimate, and whether or not the feature is available on a specific device, there are firmwares in the wild giving that flexibility.
This is the report we have: https://rink.hockeyapp.net/manage/apps/11060/app_versions/34145501/crash_reasons/133684546

We can ofc speculate (e.g. app just installed prior to permission request and crashed fresh on installation) but I would rather act out of evidence. It _is_ possible not to have the permission. It is a legitimate idea not to allow _any_ application have it. Other application developers may decide to not request the permission at all - and you are saying they will be unable to use HockeyApp by design.

**Comment by aromanovsky** [comment] 2016-08-30 08:21
...and I was right about the firmware. The issue is predominantly affecting LG VS990, LG-H900, LG-H901 and like on OS 6.0 (I did not say "exclusively" to avoid paging through all the 1600 traces).

**Comment by aromanovsky** [comment] 2016-08-30 08:27
> what would be the motivation of a user to be deliberately revoking the permission to access the network state but allowing for the app to try and transmit data anyway without e.g. revoking the INTERNET permission anyway

Accessing - even merely reading - the network state (i.e. the way the user connects to the network, which includes carriers, WiFi SSIDs etc.) is not critical to the functionality of a communication app; hence, it SHOULD NOT be exposed; and if the application deliberately requests it, then something is wrong with the app and the permission MUST NOT be exposed. I am not obsessed with security, but I know there are a lot of people who do, and many of them for good reasons.

**Comment by ranterle** [comment] 2016-08-30 08:39
According to the official documentation, the `ACCESS_NETWORK_STATE` permission is granted automatically upon installation, when it is listed in the manifest. The documentation is not clear on  whether permissions granted this way can be revoked later through ADB – our test devices don't allow for changing the permission later, so we can't verify it.
How did you find out about the affected devices, are those devices affected by the crash group you are referring to?
We don't have access to customers crash reports for privacy reasons. I'd suggest opening a [support request](https://support.hockeyapp.net) and share the stack trace with us there.

The application developer does not have to request this permission - we are requesting it in our manifest and this gets merged into the apps manifest. So I don't see how it would go amiss for users unless they actively revoke the permission _after_ app installation.

In theory, accessing the network state would not be relevant to sending data. But like I said, in practice we had issues where this was the only safe guard against weird crashes caused by a network connection not being available.

After all, the SDK is open source - if you feel the need to alter the way it behaves you can create a PR for the proposed solution.

**Comment by aromanovsky** [comment] 2016-08-30 08:48
> are those devices affected by the crash group you are referring to?

Yes.

> share the stack trace with us there

Well, you have the trace on the ticket. I would open a support request if extra proof is required.

> unless they actively revoke the permission after app installation.

Then it means they do.

> The application developer does not have to request this permission - we are requesting it in our manifest and this gets merged into the apps manifest.

Which still means the application developer has to _ship_ the app with this permission - whether the primary app functionality requires it or not.

> in practice we had issues where this was the only safe guard against weird crashes caused by a network connection not being available.

As I put above, nothing can be reliable about a network I/O operation in general, in particular *no check made beforehand*. Catch everything thrown (you already have a dedicated network thread, so that would be a narrowly focused change), retry later, that's the only way to go.

Did you have _native_ crashes because of a network operation in a prohibited state?

> if you feel the need to alter the way it behaves you can create a PR for the proposed solution.

That's what I will probably do. Thanks you for providing the context!

**Closed** 2016-11-15 00:57 UTC
Labels: bug
