### ISSUE TITLE
Impossible to request WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by Ufkoku** [bitstadium/HockeySDK-Android#359] opened 2018-02-13 13:30 UTC
After including `implementation 'net.hockeyapp.android:HockeySDK:5.1.0'` dependency to android project it is impossible to request WRITE_EXTERNAL_STORAGE permission - the result is always false.  
It happens after manifest merging, because of line 8 in [AndroidManifext.xml](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/AndroidManifest.xml):  
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18" />`

**Comment by MatkovIvan** [comment] 2018-02-13 13:32
Hi,

This is described in our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0):
> To be ready for Android O, HockeySDK-Android now limits the WRITE_EXTERNAL_STORAGE permission with the maxSdkVersion filter. In some use cases, e.g. where an app contains a dependency that requires this permission, maxSdkVersion makes it impossible for those dependencies to grant or request the permission. The solution for those cases is to declare the tools:node="replace" manifest merging strategy later in the dependency tree:
 `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

Best,
Ivan

**Comment by MatkovIvan** [comment] 2018-02-13 13:33
Another duplicate of #301

**Closed** 2018-02-19 17:54 UTC
