### ISSUE TITLE
Crash report with XposedBridge.

### ISSUE THREAD

**Issue by MidasCE** [bitstadium/HockeySDK-Android#428] opened 2019-06-18 09:34 UTC
We got a crash from our app that possible come from the hockeyApp sdk. (right now we use v.5.2.0)

The crash is come from `XposedBridge` which located inside of HockeyApp sdk. (Since our app not using the XposedBridge.

The crash only happen to Xperia Z5 user, Android version 7.1.1

```Caused by android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:371)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
       at android.webkit.WebView.getFactory(WebView.java:2325)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2320)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2379)
       at android.view.View.(View.java:4071)
       at android.view.View.(View.java:4194)
       at android.view.ViewGroup.(ViewGroup.java:579)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java:55)
       at android.webkit.WebView.(WebView.java:627)
       at android.webkit.WebView.(WebView.java:572)
       at android.webkit.WebView.(WebView.java:555)
       at android.webkit.WebView.(WebView.java:542)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
       at android.view.LayoutInflater.inflate(LayoutInflater.java)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
       at net.hockeyapp.android.UpdateFragment.getLayoutView(UpdateFragment.java:287)
       at net.hockeyapp.android.UpdateFragment.onCreateView(UpdateFragment.java:133)
       at android.app.Fragment.performCreateView(Fragment.java:2353)
       at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:999)
       at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1175)
       at android.app.BackStackRecord.run(BackStackRecord.java:816)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1589)
       at android.app.FragmentController.execPendingActions(FragmentController.java:371)
       at android.app.Activity.performStart(Activity.java:6736)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2683)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:6274)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

Caused by android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:270)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:330)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
       at android.webkit.WebView.getFactory(WebView.java:2325)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2320)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2379)
       at android.view.View.(View.java:4071)
       at android.view.View.(View.java:4194)
       at android.view.ViewGroup.(ViewGroup.java:579)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java:55)
       at android.webkit.WebView.(WebView.java:627)
       at android.webkit.WebView.(WebView.java:572)
       at android.webkit.WebView.(WebView.java:555)
       at android.webkit.WebView.(WebView.java:542)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
       at android.view.LayoutInflater.inflate(LayoutInflater.java)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
       at net.hockeyapp.android.UpdateFragment.getLayoutView(UpdateFragment.java:287)
       at net.hockeyapp.android.UpdateFragment.onCreateView(UpdateFragment.java:133)
       at android.app.Fragment.performCreateView(Fragment.java:2353)
       at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:999)
       at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1175)
       at android.app.BackStackRecord.run(BackStackRecord.java:816)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1589)
       at android.app.FragmentController.execPendingActions(FragmentController.java:371)
       at android.app.Activity.performStart(Activity.java:6736)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2683)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:6274)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)```

**Comment by annakocheshkova** [comment] 2019-06-18 10:16
Hi @MidasCE, this crash is likely to be caused by the `WebView` itself updating at the moment of the call. Does this reproduce repeatedly or it was a one-time crash?

**Comment by MidasCE** [comment] 2019-06-18 10:29
The crash is happen from times to times for some user and it log into Crashlytics.

**Comment by annakocheshkova** [comment] 2019-06-18 11:44
Since Android 5, Webview has been shipping as a separate app and it is being updated by Play Store, so you can safely ignore these kinds of exceptions. They do not break anything and should be quite rare (only at the time WebView is updated). 
If you really want to "swallow" these kinds of exceptions, you can wrap the update calls with `try .. catch` and ignore them as described [here](https://stackoverflow.com/a/46266199/7453375), but it seems like a bit of an overkill.
I'm going to close this. Feel free to re-open if you need anything else.

**Closed as completed by annakocheshkova** 2019-06-18 11:44 UTC
