### ISSUE TITLE
SendFeedbackTask crashes if no Internet available

### ISSUE THREAD

**Issue by OnlyInAmerica** [bitstadium/HockeySDK-Android#174] opened 2016-09-07 22:12 UTC
`SendFeedbackTask#doInBackground` throws an uncaught exception if no Internet is available because it seems [HttpURLConnectionBuilder.build()](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/tasks/SendFeedbackTask.java#L278) throws a `RuntimeException` if no address for the given host is available:

```
java.net.UnknownHostException: Unable to resolve host "sdk.hockeyapp.net": No address associated with hostname
```

**Comment by ranterle** [comment] 2016-11-15 00:57
Sorry for the long delay. Unfortunately we're not able to reproduce this. There are network guards in place which should catch the case of no network connectivity, can you tell us the specific steps to reproduce this?

**Comment by ranterle** [comment] 2016-12-02 15:46
Closing this as non-reproducible - please reopen this if it occurs again.

**Closed by ranterle** 2016-12-02 15:46 UTC
Labels: bug
