### ISSUE TITLE
Can't disable autosend on 5.0.0

### ISSUE THREAD

**Issue by yuriy-budiyev** [bitstadium/HockeySDK-Android#280] opened 2017-08-18 15:10 UTC
Auto send is enabled by default, if context is not instance of Activity.
CrashManagerListener#shouldAutoUploadCrashes() is ignored.
But if i'll initialize CrashManager with Activity context it will not be able to save crashes when my LauncherActivity will be closed.

**Comment by yuriy-budiyev** [comment] 2017-08-18 15:17
Please add something to control auto send behavior

**Comment by yuriy-budiyev** [comment] 2017-08-18 15:41
Btw, i found the ugly solution. Initialize CrashManager with app context when processing finished. In my app, I strictly need to ask user whether send crashes or not.

**Comment by MatkovIvan** [comment] 2017-08-18 16:04
Hi, @yuriy-budiyev!
Thanks for keeping in touch!
This behavior wasn't introduced in `5.0.0`. (See [`4.0.0 sources`](https://github.com/bitstadium/HockeySDK-Android/blob/4.0.0/hockeysdk/src/main/java/net/hockeyapp/android/CrashManager.java#L173-L182) for example)
The cause that is: we able to show dialog from activity context only.

**Comment by MatkovIvan** [comment] 2017-08-18 16:29
I created PR to you can show UI for ask (in `onHandleAlertView` callback).

**Comment by yuriy-budiyev** [comment] 2017-08-18 16:35
I aleady done this in my app, overrided onHandleAlertView, and show alert from activity context. And it worked well, when I called initialize method with app context, and execute method with activity context. In 5.0.0 execute method does not have context argument.

**Comment by yuriy-budiyev** [comment] 2017-08-18 16:39
Also, it will be good to add to CrashManagerListener callback onNoCrashesFound, or something like this.

**Comment by MatkovIvan** [comment] 2017-08-18 17:27
> In 5.0.0 execute method does not have context argument.

Got it. I guess this should be reverted.


> Also, it will be good to add to CrashManagerListener callback onNoCrashesFound, or something like this.

Good point. Done in the same PR.

**Comment by yuriy-budiyev** [comment] 2017-08-20 20:50
I don't think reverting is necessary, simly add ability to show overriden alert dialog from app context.

**Comment by TroubleMakerBen** [comment] 2017-09-01 06:30
We just released HockeySDK 5.0.0, so I'm closing this.

**Closed by TroubleMakerBen** 2017-09-01 06:30 UTC
