### ISSUE TITLE
WRITE_EXTERNAL_STORAGE permission is removed by HockeyApp

### ISSUE THREAD

**Issue by smuldr** [bitstadium/HockeySDK-Android#356] opened 2018-01-26 16:43 UTC
The HockeyApp SDK sets an `android:maxSdkVersion="18"` attribute on the WRITE_EXTERNAL_STORAGE permission in its AndroidManifest, which removes the permission on higher API levels. I don't know why this attribute is there, but it is causing problems in our app. 

Example: Our app uses LeakCanary and Spoon, both of which require this permission to work correctly. Even though we put the `<uses-permission>` tag in our debug AndroidManifest, these tools always fail. Apparently the merged manifest also contains the `android:maxSdkVersion` attribute. These kind of hidden attributes are very difficult to discover. I actually thought it was some new security policy in Android that was causing LeakCanary to fail.

Is it possible to remove the attribute from the SDK, and leave the permissions up to the end user? Perhaps HockeyApp can print a warning in the Logs or a show Toast if the permission is missing.

**Comment by smuldr** [comment] 2018-01-26 16:44
For anyone having the same issue, you can remove the `android:MaxSdkVersion` attribute from the merged manifest as follows.
```xml
<uses-permission
    android:name="android.permission.WRITE_EXTERNAL_STORAGE"
    tools:remove="android:maxSdkVersion" />
```

**Comment by MatkovIvan** [comment] 2018-01-26 16:46
Duplicate of #301

**Comment by MatkovIvan** [comment] 2018-01-26 16:48
Hi @smuldr,

This is described in our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0):
> To be ready for Android O, HockeySDK-Android now limits the WRITE_EXTERNAL_STORAGE permission with the maxSdkVersion filter. In some use cases, e.g. where an app contains a dependency that requires this permission, maxSdkVersion makes it impossible for those dependencies to grant or request the permission. The solution for those cases is to declare the tools:node="replace" manifest merging strategy later in the dependency tree:
 `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

Best,
Ivan

**Comment by Iqra786** [comment] 2018-02-22 14:40
Hi,

I have tried all solution but no success.

**Comment by TroubleMakerBen** [comment] 2018-02-22 18:40
Hi @Iqra786,

have you tried `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>` as well as
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"    tools:node="remove" />`?

**Comment by Iqra786** [comment] 2018-02-23 08:31
Hi, @TroubleMakerBen 

Yes, I have tried both.

**Comment by TroubleMakerBen** [comment] 2018-02-23 18:30
Is there any chance you can send us the project (or a sample that has this behavior)? We cannot repro this and I'm running out of ideas. To do that, please contact us via [Support](https://support.hockeyapp.net) and mention this conversation.

Thx a ton!

**Comment by tobi512** [comment] 2018-03-27 09:37
@Iqra786 @TroubleMakerBen 
I can confirm that replacing the `maxSdkVersion` works as expected for us with the following ways: `tools:node="replace"` and `tools:remove="android:maxSdkVersion"`. 
However, `tools:node="remove"` only removes the permission itself and not the `maxSdkVersion` restriction, so **don't use** this!

We also have Spoon and LeakCanary besides HockeySDK in our project, did you make sure to check your merged manifest (tab "Merged Manifest" in Android Studio).
If you have multiple manifest files in your project for more than one module, you should also check if the right one is used. 

The following screenshots show the difference in our final merged manifest (first one without the additional code, resulting in the `maxSdkVersion` to be _incorrectly_ present, and the second one with the `maxSdkVersion` replaced/removed _correctly_). 

<img width="668" alt="maxsdkversionpresent" src="https://user-images.githubusercontent.com/2721729/37958949-23b81fd2-31b2-11e8-8ec5-bd8631c4352c.png">
<img width="667" alt="maxsdkversionremoved" src="https://user-images.githubusercontent.com/2721729/37958959-295fce94-31b2-11e8-8bc1-b418745d04bf.png">

Hope this helps you in finding your problem cause...

Btw: don't ask me why the READ_EXTERNAL_STORAGE permission occurs twice in the final merge result 😄

**Comment by rusmonster** [comment] 2018-07-24 12:12
Adding tools:node="replace" helps for me, but now I have

`
Task :app:processDebugManifest 
/Android/app/AndroidManifest.xml:6:2-131 Warning:
        uses-permission#android.permission.WRITE_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:6 to replace another declaration but no other declaration present
`

Any ideas how to avoid or at least suppress it?

**Comment by jaelim-ms** [comment] 2018-07-24 20:45
@rusmonster The warning tells you that you don't have any tags to be replaced. Looks like your project doesn't contain HockeyApp dependencies, can you make sure your app contains HockeyApp libraries in it?

**Comment by rusmonster** [comment] 2018-07-25 06:40
@jaelim-ms Yes, I'm sure my app contains hockeyApp. Moreover, without `tools:node="replace"` hockeyApp drops WRITE_EXTERNAL_STORAGE in my app on API > 18 and adding the `tools:node="replace"` returns it back. So the warning looks like manifest merger issue. I'm just asking about how to suppress it?

**Comment by jaelim-ms** [comment] 2018-07-25 19:17
@rusmonster I've tried to find a way to suppress the warning but couldn't find any. Sorry about that. I keep searching it and let you know if I find but the warning isn't from lint so I don't think you can suppress it.

**Comment by jaelim-ms** [comment] 2018-07-30 18:15
We have another open issue regarding the permission issue. Please continue conversation in #373.

**Closed by jaelim-ms** 2018-07-30 18:15 UTC
