### ISSUE TITLE
Problem with WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by AyoPrez** [bitstadium/HockeySDK-Android#357] opened 2018-01-30 15:43 UTC
In a Nexus 5 with Android M:

The WRITE_EXTERNAL_STORAGE permission is always denied, even if it's granted in the settings. This doesn't happen in the 4.1.5, but start to happen in the 5.0.0 version

**Comment by MatkovIvan** [comment] 2018-01-30 15:46
Duplicate of #301

**Comment by MatkovIvan** [comment] 2018-01-30 15:46
Hi @AyoPrez,

This is described in our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0):
> To be ready for Android O, HockeySDK-Android now limits the WRITE_EXTERNAL_STORAGE permission with the maxSdkVersion filter. In some use cases, e.g. where an app contains a dependency that requires this permission, maxSdkVersion makes it impossible for those dependencies to grant or request the permission. The solution for those cases is to declare the tools:node="replace" manifest merging strategy later in the dependency tree:
 `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

Best,
Ivan

**Closed** 2018-01-30 16:03 UTC
