### ISSUE TITLE
Why you are using  (android:maxSdkVersion="18") for WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by soulaimenk** [bitstadium/HockeySDK-Android#351] opened 2018-01-15 13:55 UTC
I think you should remove the maxSdkVersion from (HockeyApp:Manifest). It'll affect the whole project Manifest:
```
<uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="18" />
```

**Comment by MatkovIvan** [comment] 2018-01-15 14:05
Hey @soulaimenk 

Thanks for getting in touch!

Example from [android docs](https://developer.android.com/guide/topics/manifest/uses-permission-element.html) is exactly our case:
> Beginning with Android 4.4 (API level 19), it's no longer necessary for your app to request the `WRITE_EXTERNAL_STORAGE` permission when your app wants to write to its own application-specific directories on external storage


You can just declare the `tools:node="replace"` manifest merging strategy later in the dependency tree:
 `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`. This is described in our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0).


Duplicate of #301

Best,
Ivan

**Closed** 2018-01-15 14:16 UTC

**Comment by asadwaheed1** [comment] 2019-09-19 13:24
> 
> 
> Hey @soulaimenk
> 
> Thanks for getting in touch!
> 
> Example from [android docs](https://developer.android.com/guide/topics/manifest/uses-permission-element.html) is exactly our case:
> 
> > Beginning with Android 4.4 (API level 19), it's no longer necessary for your app to request the `WRITE_EXTERNAL_STORAGE` permission when your app wants to write to its own application-specific directories on external storage
> 
> You can just declare the `tools:node="replace"` manifest merging strategy later in the dependency tree:
> `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`. This is described in our [documentation](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#integrate-sdk) and [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0).
> 
> Duplicate of #301
> 
> Best,
> Ivan

Thank you, I am not using this library but your reply helped me with my project. I was stuck from yesterday.
