### ISSUE TITLE
Wrong permission in Manifest

### ISSUE THREAD

**Issue by robohorse** [bitstadium/HockeySDK-Android#382] opened 2018-07-06 10:37 UTC
Hi, you do awesome project and we like to use it, but there are some problems since to version 5.0. You added this 
```
android:maxSdkVersion="18"
```
to 
```
WRITE_EXTERNAL_STORAGE
```
permission and it affects android permission check. see [this](https://stackoverflow.com/a/40775623/4357850) thread.

Can you remove it plz from your manifest?

**Comment by MatkovIvan** [comment] 2018-07-06 10:50
Duplicate of #373

**Comment by TroubleMakerBen** [comment] 2018-07-11 00:30
I'm closing this as it's a duplicate of #373

**Closed by TroubleMakerBen** 2018-07-11 00:30 UTC
