### ISSUE TITLE
ANR when calling ExceptionHandler#saveException with HockeyApp SDK v5.0.3

### ISSUE THREAD

**Issue by TFR258** [bitstadium/HockeySDK-Android#322] opened 2017-10-24 14:22 UTC
Hi everyone,

We have seen a couple of instances of ANRs with the following thread trace.

```
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x74630bb0 self=0x7fa8ea3a00
  | sysTid=25876 nice=0 cgrp=default sched=0/0 handle=0x7fadc9b9b0
  | state=S schedstat=( 97180709 7117185 529 ) utm=6 stm=2 core=4 HZ=100
  | stack=0x7fd9947000-0x7fd9949000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x0aed0fbe> (a java.lang.Object)
  at java.lang.Thread.parkFor$(Thread.java:2159)
  - locked <0x0aed0fbe> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
  at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:450)
  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  at net.hockeyapp.android.ExceptionHandler.void saveException(java.lang.Throwable,java.lang.Thread,net.hockeyapp.android.CrashManagerListener)(ExceptionHandler.java:109)
```

It seems like calls to `Constants.getDeviceIdentifier().get()` get blocked for more than 5 seconds.
Can you help us understand why this is happening?

Thank you.

**Comment by MatkovIvan** [comment] 2017-10-24 14:41
Hi @TFR258 

Thanks for getting in touch.
It looks like you didn't initialize any manager from SDK.
If you don't want to do it for some reason you can also initialize `Constants` directly via `Constants.loadFromContext` call. But I highly recommend initializing SDK in the documented way.

Thanks,
Ivan

**Comment by TFR258** [comment] 2017-10-24 15:00
Hi @MatkovIvan,

Thank you for the fast response

I have just doubled checked our source. We are initialising the Hockey App SDK as soon as possible using `CrashManager.register()`.
Can this issue only occur if the HockeyApp SDK hasn't been initialised?

**Comment by MatkovIvan** [comment] 2017-10-24 15:51
Yes, [getDeviceIdentifier()](https://github.com/bitstadium/HockeySDK-Android/blob/5.0.3/hockeysdk/src/main/java/net/hockeyapp/android/Constants.java#L94-L106) just wait for initialization. Maybe you have errors during initialization? Is there any other useful information in the logs (Use `HockeyLog.setLogLevel(Log.VERBOSE);` to get more details)?

**Comment by TFR258** [comment] 2017-10-25 13:16
Hi @MatkovIvan,

We haven't seen anything suspicious in the logs. I'll run a couple of monkeys with the provided HockeyApp log level to see if anything emerges.

We suspect this might be due to a race condition.
 Is there a way of checking whether the SDK is initialised?

**Comment by MatkovIvan** [comment] 2017-10-25 13:46
I've realized the root cause. It will be fixed in next release.
Thanks for reporting!

**Comment by TFR258** [comment] 2017-10-25 14:02
Hi @MatkovIvan,

Thank you for the good news.
Do you know when the next version of HockeyApp will be released?

**Comment by TroubleMakerBen** [comment] 2017-10-25 16:07
Hey @TFR258 
We're currently targeting 2nd half of November.

Best,
Benjamin

**Closed** 2017-10-25 16:08 UTC
